### ISSUE TITLE
Does not function properly when Chrome is not installed

### ISSUE THREAD

**Issue by crushv** [droibit/CustomTabsLauncher#1]
In my case I do not have any Chrome build installed on my device, only Chromium and Firefox (which are both custom tabs compatible). It could be possible to fallback to a dialog asking users which browser they'd like to use.

**Comment by droibit** [comment]
I have added a new class to launch other browsers that support CustomTabs as Fallback in the latest v1.3.0.
- https://github.com/droibit/CustomTabsLauncher#launch-non-chrome-browsers-as-fallback
