### ISSUE TITLE
open customTabs with installed pkg

### ISSUE THREAD

**Issue by kutear** [droibit/CustomTabsLauncher#6]
there are many kind of browser to support customTbs, we can't write all pkg to `expectCustomTabsPackages`,  so it's possible to check out all application that support customTabs installed on device, then if match `expectCustomTabsPackages` we  can  choose target application, also use first application (or other) to open url, otherwise to use fallback action

sorry for my poor eng.

**Comment by droibit** [comment]
@kutear   
Sorry for the late reply.
Updated `LaunchNonChromeCustomTabs` to automatically list all non-Chrome Custom Tabs installed on the device.
```kotlin
// e.g. 
CustomTabsLauncher.launch(
    context,
    customTabsIntent,
    Uri.parse("https://www.google.com"),
    LaunchNonChromeCustomTabs(context)
)
```

This update has not been released yet, but you can temporarily change the dependencies to check if it works.
```groovy
dependencies {
    implementation 'com.github.droibit:customtabslauncher:develop-SNAPSHOT'
}
```

Feel free to give me feedback.

**Comment by droibit** [comment]
Reopen this issue if necessary.
